services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/src
    depends_on:
      - mysql
      - php
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    user: "1000:1000"
    volumes:
      - ./src:/var/www/src
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3346:3306"
    env_file:
      - env/mysql.env
    volumes:
      - db_data:/var/lib/mysql
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    user: "1000:1000"
    volumes:
      - ./src:/var/www/src
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    user: "1000:1000"
    volumes:
      - ./src:/var/www/src
    entrypoint: ["php", "/var/www/src/artisan"]
volumes:
  db_data:
